---
# Adding Web Redirect DNS Records
- name: Adding CloudFlare Records for Domains
  cloudflare_dns:
    account_email: "{{ cf_email }}"
    account_api_token: "{{ cf_key }}"
    zone: "{{ item[0] }}"
    record: "@"
    type: A
    ttl: 300
    value: "{{ item[1] }}"
    solo: yes
  loop:
    "{{ domain_assoc }}"